# Generated by Django 3.2.6 on 2025-02-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('database_name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('LENGTH_CHECK', 'Length Check'), ('NULL_OR_EMPTY_CHECK', 'Null or Empty Check'), ('ALPHABET_CHECK', 'Alphabet Check'), ('PATTERN_MATCHING', 'Pattern Matching'), ('PK_CHECK', 'Primary Key Check'), ('TIMESTAMP_CONSISTENCY_CHECK', 'Timestamp Consistency Check'), ('HASHKEY_ACCURACY_CHECK', 'Hashkey Accuracy Check'), ('CUSTOM_SQL', 'Custom SQL')], max_length=50)),
                ('execution_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('alert_recipient', models.EmailField(max_length=254)),
                ('business_critical', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('active_flag', models.IntegerField(choices=[(0, '0'), (1, '1')])),
                ('second_column', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=10, null=True)),
                ('start_value', models.CharField(blank=True, max_length=255, null=True)),
                ('end_value', models.CharField(blank=True, max_length=255, null=True)),
                ('values', models.TextField(blank=True, null=True)),
                ('threshold_value', models.CharField(blank=True, max_length=255, null=True)),
                ('like_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_sql', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Quality Check',
                'verbose_name_plural': 'Data Quality Checks',
                'db_table': 'data_quality_checks',
            },
        ),
    ]
