# Generated by Django 3.2.6 on 2025-02-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualitycheck',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
